### PR TITLE
Update doc for GPS and Time/Location

### PR DESCRIPTION
**Pull request by naheedsa**

### CODE REVIEW

**Comment by knro** [comment]
Why 171 files changed? I can't find the actual change

**Comment by naheedsa** [comment]
It got changed after regenerating the new HTML.
This is the file for TimeLocation and GPS but it is an HTML code.

https://github.com/ikarustechnologies/stellarmatewebmanual/blob/062b108291b2bd584ea9e9f13f0c759738a749d5/TimeLocation.html

https://github.com/ikarustechnologies/stellarmatewebmanual/blob/062b108291b2bd584ea9e9f13f0c759738a749d5/GPS.html

**Comment by knro** [comment]
Are you using the latest version of the program I sent to you?

**Comment by naheedsa** [comment]
> Are you using the latest version of the program I sent to you?

No, I will update it but if I make more changes then it update other files as well.
I will install that and regenerate the manual

**Comment by knro** [comment]
Ok please use latest version since we paid for this

**Comment by naheedsa** [comment]
Generated HTML using latest HelpNDoc version

**Pull request merged**
